import "./globals.css";

// import MainLayout from "@/components/layouts";

// const inter = Saira({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <MainLayout /> */}
        <div>{children}</div>
      </body>
    </html>
  );
}
